core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "core"

urlpatterns = [
    path('', views.landing_page, name='landing'),
]

if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path, include

from . import views

app_name = "doctor"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('appointment', views.Appointment.as_view(), name='appointment'),
    path('appointment/past', views.PastAppointment.as_view(), name='past_appointments'),
    path('appointment/<int:pk>/update', views.UpdateAppointment.as_view(), name='update'),
    path('appointment/<int:pk>/cancel', views.CancelAppointment.as_view(), name='cancel'),
    path('appointment/<int:pk>/complete', views.CompleteAppointment.as_view(), name='complete'),
    path('appointment/<int:pk>/start', views.StartAppointment.as_view(), name='start'),
    path('patient/<int:id>', views.Patient_detail.as_view(), name='patient_detail'),
    path('chest-analysis', views.Analysis.as_view(), name='analysis')
    
]

fypDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import landing_page



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('doctor/', include('doctor.urls') ),
    path('administrator/', include('administrator.urls') ),
    path('radiologist/', include('radiologist.urls') ),
    path('patient/', include('Patient.urls') ),
    path('', include('core.urls') ),
    path('register/', include('register.urls')),
    path('', include("django.contrib.auth.urls")),
]

radiologist/urls.py
from django.urls import path, include

from . import views

app_name = "radiologist"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('chest-analysis', views.Analysis.as_view(), name='analysis'),
    path('referal', views.Referal.as_view(), name='referal'),
    path('referal/past', views.PastReferal.as_view(), name='past'),
    path('referal/<int:pk>/start', views.ReferalStart.as_view(), name='start'),
    path('referal/<int:pk>/cancel', views.ReferalCancel.as_view(), name='cancel'),
]

core/models.py
from datetime import date
from django.db import models
from register.models import Patient, Radiologist, Doctor



# APPOINTMENT MODEL
TYPES = (('consult', 'Consultation'), ('follow', 'Follow-up'),)
STATUS = (('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'),)

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, related_name='appoint_patient')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, related_name='appoint_doctor')
    description = models.TextField()
    date = models.DateField('Date')
    start_time = models.TimeField('Start Time', null=True)
    types = models.CharField(max_length=100, choices=TYPES)
    status = models.CharField(max_length=100, choices=STATUS)
    mcheck = models.BooleanField(default=False)
    rcheck = models.BooleanField(default=False)

    def __str__(self):
        return str(self.date)




# GLOBAL VARIABLES
Rad_types = (
    ('x', 'X-Ray'),
    ('ct', 'CT-Scan'),
    ('mri', 'MRI'),
    ('ot', 'Others'),
)

Body_location = (
    ('ab', 'Abdomen'),
    ('ch', 'Chest'),
    ('pl', 'Pelvis'),
    ('ue', 'Upper Extremities'),
    ('le', 'Lower Extremities'),
    ('sp', 'Spine'),
    ('hnf', 'Head, Neck and Face'),
    ('ot', 'Others'),
)




# REPORTS MODEL
Rep_type = (
    ('rad', 'Radiology'),
    ('med', 'Medical'),
)

class Report(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, related_name='report_patient')
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True, related_name='report_doctor')
    radiologist = models.ForeignKey(Radiologist, on_delete=models.SET_NULL, null=True, blank=True, related_name='report_radiologist')
    report_type = models.CharField('Report Type', max_length=100, choices=Rep_type)
    date = models.DateField('Date', default=date.today)
    analysis = models.TextField('Analysis', null=True, blank=True)
    comments = models.TextField('Comments', null=True, blank=True)
    
    def __str__(self):
        return str(self.report_type)



class RadManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(report_type='rad')

class MedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(report_type='med')



class Radreport(Report):
    objects = RadManager()
    rad_types = models.CharField('Test Type', max_length=100, choices=Rad_types, default='ot')
    body = models.CharField('Body Location', max_length=100, choices=Body_location, default='ot')
    rad_image = models.ImageField(upload_to='rad_reports/', null = True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.report_type = 'rad'
        return super().save(*args, **kwargs)


class Medreport(Report):
    objects = MedManager()
    visit_reason = models.TextField('Visit Reason', null = True, blank=True)
    Prescription = models.TextField('Prescription', null = True, blank=True)
    med_image = models.ImageField(upload_to='med_reports/', null = True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.report_type = 'med'
        return super().save(*args, **kwargs)






# REFERAL MODAL
ref_status = (
    ('pending', 'Pending'),
    ('completed', 'Completed'),
    ('cancelled', 'Cancelled')
)

class Referal(models.Model):
        patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True, related_name='referal_patient')
        rad_report = models.ForeignKey(Radreport, on_delete=models.SET_NULL, null=True, blank=True, related_name='rad_report')    #similar as radrep. Reso;ve this issue
        doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True, related_name='referal_doctor')
        radiologist = models.ForeignKey(Radiologist, on_delete=models.SET_NULL, null=True, blank=True, related_name='referal_radiologist')  #Radiologist is mandotory
        rad_types = models.CharField('Test Type', max_length=100, choices=Rad_types, default='ot', blank=True)
        body = models.CharField('Body Location', max_length=100, choices=Body_location, default='ot', blank=True)
        description = models.TextField('Description', null=True, blank=True)    #Description is Mandatory
        status = models.CharField('Status', max_length=100, choices=ref_status, default='pending')
        date = models.DateField('Date', default=date.today)
        radrep = models.ForeignKey(Radreport, on_delete=models.DO_NOTHING, null=True, blank=True)
        
        def __str__(self):
            return str(self.rad_types)

radiologist/models.py
from django.db import models

# Create your models here.

radiologist/forms.py
from dataclasses import Field
from django import forms
from django.forms import ModelForm
from django.core.validators import FileExtensionValidator

from core.models import Appointment, Radreport, Referal

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML
from crispy_bootstrap5.bootstrap5 import FloatingField



class RadReportForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_show_errors = False
        self.helper.layout = Layout(


            Row(
                Column(FloatingField('rad_type', css_class='form-group col-md-6 mb-0 hovercolor')),
                Column(FloatingField('body', css_class='form-group col-md-6 mb-0 hovercolor')),
                css_class='form-row'
            ),

            FloatingField('analysis', css_class="hovercolor"),
            FloatingField('comments', css_class="hovercolor"),
            FloatingField('rad_image', css_class="hovercolor"),
            
        )

    class Meta:
        model = Radreport
        fields = ["rad_types", "body", "analysis", "comments", "rad_image"]

radiologist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from pathlib import Path



from django.contrib import messages
from .forms import RadReportForm
from doctor.forms import ImageUploadForm
from register.models import Patient, Doctor, Radiologist
from core.models import Referal as refer
from doctor.models import Tempstorage as tmp
from core.MLmodels import Classify as classify




# DASHBOARD INDEX VIEW
class Dash(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'r':
            return render(request, 'radiologist/dashboard.html', {'type':request.user.account_type})
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# REFERAL VIEW
class Referal(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'r':
            list = refer.objects.filter(radiologist=request.user).exclude(status='completed').exclude(status='cancelled').order_by('-date')
            return render(request, 'radiologist/referal.html', {'list':list, 'type':request.user.account_type})
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# REFERAL START VIEW
class ReferalStart(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request, pk):
        
        if request.user.account_type == 'r':
            ref = get_object_or_404(refer, pk=pk)
            form = RadReportForm()
            ctx = {'form':form, 'rid':ref.id, 'type':request.user.account_type}
            return render(request, 'radiologist/start_referal.html', ctx)
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')
    
    
    def post(self, request, pk):
        
        if request.user.account_type == 'r':
            ref = get_object_or_404(refer, pk=pk)
            form = RadReportForm(request.POST, request.FILES)
            
            if not form.is_valid():
                ctx = {'form':form, 'rid':ref.id, 'type':request.user.account_type}
                return render(request, 'radiologist/start_referal.html', ctx)
            
            report = form.save(commit=False)
            report.patient = ref.patient
            report.doctor = ref.doctor
            report.radiologist = ref.radiologist
            report.save()
            ref.radrep = report
            ref.status = 'completed'
            ref.save()
            return redirect("radiologist:referal")
            
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# PAST REFERAL VIEW
class PastReferal(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'r':
            list = refer.objects.filter(radiologist=request.user).exclude(status='pending').order_by('-date')
            return render(request, 'radiologist/past_referals.html', {'list':list, 'type':request.user.account_type})
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# CANCEL REFERAL
class ReferalCancel(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    
    def get(self, request, pk):
        if request.user.account_type == 'r':
            rfr = get_object_or_404(refer, pk=pk)
            rfr.status = 'cancelled'
            rfr.save()
            return redirect('radiologist:referal')
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# CHEST ANALYSIS
# CHEXT X-RAY ANALYSIS
class Analysis(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'r':
            form = ImageUploadForm()
            return render(request, "radiologist/analysis.html", {'form':form, 'check':False, 'type':request.user.account_type})
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')

    def post(self, request):
        
        if request.user.account_type == 'r':
            
            form = ImageUploadForm(request.POST, request.FILES)
            
            if not form.is_valid():
                return render(request, "radiologist/analysis.html", {'form':form, 'check':False, 'type':request.user.account_type})
            
            form.save()
            
            img = tmp.objects.last()
            
            
            fpath = img.image.url
            img.delete()
            result = classify(fpath)

            return render(request, "radiologist/analysis.html", {'img':fpath, 'result':result, 'check':True, 'form':form, 'type':request.user.account_type})
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')

templates/radiologist/analysis.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %} Chest X-ray Analysis {% endblock %} 



<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}




{% block content %}

<div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item">
                <a href="{% url 'radiologist:dashboard' %}">
                    <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </a>
            </li>

            <li class="breadcrumb-item active" aria-current="page"> Chest Analysis</li>
        </ol>
    </nav>
    <div class="d-flex justify-content-between w-100 flex-wrap">
        <div class="mb-3 mb-lg-0">

            
            <h1 class="h4">Chest Analysis</h1>
        </div>

    </div>
</div>


{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}


<div class="row">

    <div class="col-3"></div>
    <div class="col">
        
        <div class="card shadow mb-4" style="background-color: rgba(14, 167, 255, 0.116);">
            <div class="card-body">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy}}
            
                    <input type="submit" value="Analyze Image" class="btn btn-primary">
                </form>

            </div>
        </div>

    </div>
    <div class="col-3"></div>

</div>

{% if check %}
<div class="row">

    <div class="col-1"></div>
    <div class="col">

        <div class="card border-2 shadow mb-4">
            <div class="card-body">
                <img src="{{ img }}" alt="Analysis Image">
            </div>
        </div>

    </div>

    <div class="col">
        {% if result.prob == 0 %}
        <div class="card border-2 shadow mb-4" style="background-color: rgba(102, 255, 14, 0.116);">
        {% else %}
        <div class="card border-2 shadow mb-4" style="background-color: rgba(255, 14, 14, 0.116);">
        {% endif %}
            <div class="card-body text-center">
                <h3><span class="text-muted">Disease:</span>      {{ result.label }}</h3><br>
                <h3><span class="text-muted">Likelihood:</span>   {{ result.prob }}<span>&#37;</span></h3>
            </div>
        </div>
    </div>
    <div class="col-1"></div>

</div>
{% endif %}




{% endblock content %}




<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

templates/radiologist/referal.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %} Referals {% endblock %} 



<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}




{% block content %}

  <div class="py-4">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
          <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
              <li class="breadcrumb-item">
                  <a href="{% url 'doctor:dashboard' %}">
                      <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                  </a>
              </li>

              <li class="breadcrumb-item active" aria-current="page">Referal</li>
          </ol>
      </nav>
      <div class="d-flex justify-content-between w-100 flex-wrap">
          <div class="mb-3 mb-lg-0">

            
              <h1 class="h4">Referals </h1>
          </div>
      </div>
  </div>


  {% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}


  <div class="card border-0 shadow mb-4">

    <div class="card-body">

        <div class="table-responsive">
            <table class="table table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light">
                    <tr>
                        <th class="border-0 rounded-start">Patient</th>
                        <th class="border-0">Doctor</th>
                        <th class="border-0">Date</th>
                        <th class="border-0">Test type</th>
                        <th class="border-0">Body Location</th>
                        <th class="border-0">Actions</th>
                    </tr>
                </thead>
                <tbody>

                    {% if list %}

                        {% for referal in list %}

                                <!-- Item -->
                                <tr>
                                    <td> {{ referal.patient.get_full_name }} </td>

                                    <td> {{ referal.doctor.get_full_name }} </td>
                                    
                                    <td class="fw-bold"> {{referal.date}} </td>

                                    <td> {{ referal.get_rad_types_display }} </td>

                                    <td> {{referal.get_body_display}} </td>

                                    <td>
                                        <button type="button" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#referal{{referal.id}}">View</button>
                                        <a href="{% url 'radiologist:start' referal.id %}"><button class="btn btn-success">Start</button></a>
                                        <a href="{% url 'radiologist:cancel' referal.id %}"><button class="btn btn-danger">Cancel</button></a>
                                    </td>
                                </tr>
                                <!-- End of Item -->


                        {% endfor %}

                    {% endif %}



                </tbody>
            </table>
        </div>
    </div>

  
  </div>




                <!-- Appointment Modal -->
                {% for referal in list %}
                <div class="modal fade" id="referal{{referal.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Referal Details</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
    
                            <div class="accordion" id="accordionPanelsStayOpenExample">

                                <!-- PATIENT INFO -->
                                  <div class="accordion-item">
                                    <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                                      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                                        DOCTOR'S INFO
                                      </button>
                                    </h2>
                                    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                                      <div class="accordion-body">
                                        <ul style="color: black;">
                                              <li><strong>Refered Patient:&emsp;&emsp;</strong>{{ referal.patient.get_full_name }}</li><br>
                                              <li><strong>Referee Doctor:&emsp;&emsp;</strong>{{ referal.doctor.get_full_name }}</li><br>
                                        </ul>
                                      </div>
                                    </div>
                                  </div>
              
              
                                  <!-- DETAILS -->
                                  <div class="accordion-item">
                                    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="true" aria-controls="panelsStayOpen-collapseTwo">
                                            DETAILS
                                        </button>
                                      </h2>
                                      <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingTwo">
                                        <div class="accordion-body">
                                          <ul style="color: black;">
                                            <li><strong>Test Type:&emsp;&emsp;</strong>{{ referal.get_rad_types_display }}</li><br>
                                            <li><strong>Body Location:&emsp;&emsp;</strong>{{ referal.get_body_display }}</li><br>
                                            <li><strong>Date:&emsp;&emsp;</strong>{{ referal.date }}</li><br>
                                          </ul>
                                        </div>
                                      </div>
                                </div>
            
            
                                  <!-- DESCRIPTION -->
                                  <div class="accordion-item">
                                      <h2 class="accordion-header" id="panelsStayOpen-headingFour">
                                          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="true" aria-controls="panelsStayOpen-collapseFour">
                                              DESCRIPTION
                                          </button>
                                        </h2>
                                        <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingFour">
                                          <div class="accordion-body">
                                            <ul style="color: black;">
                                                  <li>{{ referal.description }}</li>
                                            </ul>
                                          </div>
                                        </div>
                                  </div>
                                  
                              </div><br>
    
                        </div>
                    </div>
                    </div>
                </div>
                {% endfor %}

{% endblock content %}




<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/radiologist/start_referal.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %} Start Appointment {% endblock %} 



<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}




{% block content %}

<!-- HEADERS -->
  <div class="py-4">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
          <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
              <li class="breadcrumb-item">
                  <a href="{% url 'radiologist:dashboard' %}">
                      <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                  </a>
              </li>

              <li class="breadcrumb-item"><a href="{% url 'radiologist:referal' %}">Referals</a></li>
            <li class="breadcrumb-item active" aria-current="page">Start</li>
          </ol>
      </nav>
      <div class="d-flex justify-content-between w-100 flex-wrap">
          <div class="mb-3 mb-lg-0">

            
              <h1 class="h4">Start Referal </h1>
          </div>
      </div>
  </div>


<!-- PATIENT HISTORY ROW -->
    <div class="row">

        <div class="col-1"></div>
        <div class="col">

            <div class="card border-0 shadow mb-4">

                <div class="card-header"><h2>Radiology Report</h2></div>
                <div class="card-body">
                
                
                    <form action="" method="post" enctype='multipart/form-data'>

                        {% csrf_token %}
                        {{ form | crispy }}
            
                        <input type="submit" value="Complete & Submit" class="btn btn-success">
                        <a href="{% url 'radiologist:cancel' rid %}"><button class="btn btn-danger">Cancel</button></a>
            
                    </form>
    
                </div>

            </div>
    
        </div>
        <div class="col-1"></div>
    </div> 





{% endblock content %}




<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}