core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "core"

urlpatterns = [
    path('', views.landing_page, name='landing'),
]

if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path, include

from . import views

app_name = "doctor"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('appointment', views.Appointment.as_view(), name='appointment'),
    path('appointment/past', views.PastAppointment.as_view(), name='past_appointments'),
    path('appointment/<int:pk>/update', views.UpdateAppointment.as_view(), name='update'),
    path('appointment/<int:pk>/cancel', views.CancelAppointment.as_view(), name='cancel'),
    path('appointment/<int:pk>/complete', views.CompleteAppointment.as_view(), name='complete'),
    path('appointment/<int:pk>/start', views.StartAppointment.as_view(), name='start'),
    path('patient/<int:id>', views.Patient_detail.as_view(), name='patient_detail'),
    path('chest-analysis', views.Analysis.as_view(), name='analysis')
    
]

fypDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import landing_page



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('doctor/', include('doctor.urls') ),
    path('administrator/', include('administrator.urls') ),
    path('radiologist/', include('radiologist.urls') ),
    path('patient/', include('Patient.urls') ),
    path('', include('core.urls') ),
    path('register/', include('register.urls')),
    path('', include("django.contrib.auth.urls")),
]

core/models.py
from datetime import date
from django.db import models
from register.models import Patient, Radiologist, Doctor



# APPOINTMENT MODEL
TYPES = (('consult', 'Consultation'), ('follow', 'Follow-up'),)
STATUS = (('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'),)

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, related_name='appoint_patient')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, related_name='appoint_doctor')
    description = models.TextField()
    date = models.DateField('Date')
    start_time = models.TimeField('Start Time', null=True)
    types = models.CharField(max_length=100, choices=TYPES)
    status = models.CharField(max_length=100, choices=STATUS)
    mcheck = models.BooleanField(default=False)
    rcheck = models.BooleanField(default=False)

    def __str__(self):
        return str(self.date)




# GLOBAL VARIABLES
Rad_types = (
    ('x', 'X-Ray'),
    ('ct', 'CT-Scan'),
    ('mri', 'MRI'),
    ('ot', 'Others'),
)

Body_location = (
    ('ab', 'Abdomen'),
    ('ch', 'Chest'),
    ('pl', 'Pelvis'),
    ('ue', 'Upper Extremities'),
    ('le', 'Lower Extremities'),
    ('sp', 'Spine'),
    ('hnf', 'Head, Neck and Face'),
    ('ot', 'Others'),
)




# REPORTS MODEL
Rep_type = (
    ('rad', 'Radiology'),
    ('med', 'Medical'),
)

class Report(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, related_name='report_patient')
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True, related_name='report_doctor')
    radiologist = models.ForeignKey(Radiologist, on_delete=models.SET_NULL, null=True, blank=True, related_name='report_radiologist')
    report_type = models.CharField('Report Type', max_length=100, choices=Rep_type)
    date = models.DateField('Date', default=date.today)
    analysis = models.TextField('Analysis', null=True, blank=True)
    comments = models.TextField('Comments', null=True, blank=True)
    
    def __str__(self):
        return str(self.report_type)



class RadManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(report_type='rad')

class MedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(report_type='med')



class Radreport(Report):
    objects = RadManager()
    rad_types = models.CharField('Test Type', max_length=100, choices=Rad_types, default='ot')
    body = models.CharField('Body Location', max_length=100, choices=Body_location, default='ot')
    rad_image = models.ImageField(upload_to='rad_reports/', null = True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.report_type = 'rad'
        return super().save(*args, **kwargs)


class Medreport(Report):
    objects = MedManager()
    visit_reason = models.TextField('Visit Reason', null = True, blank=True)
    Prescription = models.TextField('Prescription', null = True, blank=True)
    med_image = models.ImageField(upload_to='med_reports/', null = True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.report_type = 'med'
        return super().save(*args, **kwargs)






# REFERAL MODAL
ref_status = (
    ('pending', 'Pending'),
    ('completed', 'Completed'),
    ('cancelled', 'Cancelled')
)

class Referal(models.Model):
        patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True, related_name='referal_patient')
        rad_report = models.ForeignKey(Radreport, on_delete=models.SET_NULL, null=True, blank=True, related_name='rad_report')    #similar as radrep. Reso;ve this issue
        doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True, related_name='referal_doctor')
        radiologist = models.ForeignKey(Radiologist, on_delete=models.SET_NULL, null=True, blank=True, related_name='referal_radiologist')  #Radiologist is mandotory
        rad_types = models.CharField('Test Type', max_length=100, choices=Rad_types, default='ot', blank=True)
        body = models.CharField('Body Location', max_length=100, choices=Body_location, default='ot', blank=True)
        description = models.TextField('Description', null=True, blank=True)    #Description is Mandatory
        status = models.CharField('Status', max_length=100, choices=ref_status, default='pending')
        date = models.DateField('Date', default=date.today)
        radrep = models.ForeignKey(Radreport, on_delete=models.DO_NOTHING, null=True, blank=True)
        
        def __str__(self):
            return str(self.rad_types)

doctor/models.py
from distutils.command.upload import upload
from django.db import models
from django.core.validators import FileExtensionValidator
# Create your models here.


class Tempstorage(models.Model):
    image = models.ImageField(upload_to = "temp/", null=True, blank=True, validators=[FileExtensionValidator( ['jpg', 'jpeg', 'png'] ) ])
    

register/models.py
from dateutil.relativedelta import relativedelta
from datetime import date
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as _




class CustomManager(BaseUserManager):
    
    def create_user(self, email, username, first_name, password, **other_fields):
        
        if not email:
            raise ValueError(_('You must provide an email address'))
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, **other_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, username, first_name, password, **other_fields):
        
        if not email:
            raise ValueError("User must have an email")
        if not password:
            raise ValueError("User must have a password")
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, **other_fields)
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.save()
        
        if user.is_staff is not True:
            raise ValueError('Superuser must be assigned to is_staff=True')
        
        return user
        
        
        
        
        
        

class CustomUser(AbstractBaseUser, PermissionsMixin):
    type_choices = (
        ('p', 'Patient'),
        ('d', 'Doctor'),
        ('r', 'Radiologist'),
        ('a', 'Admin')
    )
    
    
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=200, unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200, blank=True)
    account_type = models.CharField('Type', max_length=100, choices=type_choices, default='a')
    date_joined = models.DateTimeField(default=timezone.now)
    profile_image = models.ImageField(upload_to='profile_images/', default='profile_images/default.jpg')
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name']
    
    objects = CustomManager()
    
    def __str__(self):
        return self.username
    
    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)










class PatientManager(CustomManager):
    def get_queryset(self):
        return super().get_queryset().filter(account_type='p')


class DoctorManager(CustomManager):
    def get_queryset(self):
        return super().get_queryset().filter(account_type='d')


class RadiologistManager(CustomManager):
    def get_queryset(self):
        return super().get_queryset().filter(account_type='r')






Genders = (
    ('m', 'Male'),
    ('f', 'Female'),
)

class Patient(CustomUser):
    objects = PatientManager()
    
    gender = models.CharField('Gender', max_length=50, choices=Genders, default='m')
    dob = models.DateField('Date Of Birth', null=True)


    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name) 

    def save(self, *args, **kwargs):
        if not self.pk:
            self.account_type = 'p'
        return super().save(*args, **kwargs)

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)
    
    def get_age(self):
        now = date.today()
        rdelta = relativedelta(now, self.dob)
        return rdelta.years






SPECS = (
    ('gp', 'General Physician'),
    ('p', 'Pulmonology'),
    ('r', 'Radiology'),
    ('o', 'Oncology'),    
)

class Doctor(CustomUser):
    objects = DoctorManager()
    specialization = models.CharField('Specialization', max_length=500, choices=SPECS, default='gp')
    pmc = models.CharField('PMC Registeration No', max_length=100)


    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.account_type = 'd'
        return super().save(*args, **kwargs)

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)







class Radiologist(CustomUser):
    objects = RadiologistManager()

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.account_type = 'r'
        return super().save(*args, **kwargs)

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

doctor/forms.py
from dataclasses import Field
from django import forms
from django.forms import ModelForm
from django.core.validators import FileExtensionValidator

from core.models import Appointment, Medreport, Referal
from .models import Tempstorage

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, HTML
from crispy_bootstrap5.bootstrap5 import FloatingField

class TimePickerInput(forms.TimeInput):
        input_type = 'time'

class DatePickerInput(forms.DateInput):
        input_type = 'date'

class TimeForm(ModelForm):
    
    start_time = forms.TimeField(widget=TimePickerInput)
    date = forms.DateField(widget=DatePickerInput)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_show_errors = False
        self.helper.layout = Layout(

            FloatingField('date', css_class="hovercolor"),
            FloatingField('start_time', css_class="hovercolor"),
            
        )
    
    class Meta:
        model = Appointment
        fields=('date', 'start_time',)



class MedReportForm(forms.ModelForm):
    

    class Meta:
        model = Medreport
        fields = ["visit_reason", "analysis", "comments", "Prescription", "med_image"]



class ReferalForm(ModelForm):
    
    class Meta:
        model = Referal
        fields = ["radiologist", "rad_types", "body", "description"]


class ImageUploadForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_show_errors = False
        self.helper.layout = Layout(

            FloatingField('image', css_class="hovercolor"),
            FloatingField('start_time', css_class="hovercolor"),
            
        )
    
    class Meta:
        model = Tempstorage
        fields = ["image"]

templates/doctor/analysis.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %} Chest X-ray Analysis {% endblock %} 



<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
{% endblock stylesheets %}




{% block content %}

<div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item">
                <a href="{% url 'doctor:dashboard' %}">
                    <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </a>
            </li>

            <li class="breadcrumb-item active" aria-current="page"> Chest Analysis</li>
        </ol>
    </nav>
    <div class="d-flex justify-content-between w-100 flex-wrap">
        <div class="mb-3 mb-lg-0">

            
            <h1 class="h4">Chest Analysis</h1>
        </div>

    </div>
</div>


{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}


<div class="row">

    <div class="col-3"></div>
    <div class="col">
        
        <div class="card shadow mb-4" style="background-color: rgba(14, 167, 255, 0.116);">
            <div class="card-body">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy}}
            
                    <input type="submit" value="Analyze Image" class="btn btn-primary">
                </form>

            </div>
        </div>

    </div>
    <div class="col-3"></div>

</div>

{% if check %}
<div class="row">

    <div class="col-1"></div>
    <div class="col">

        <div class="card border-2 shadow mb-4">
            <div class="card-body">
                <img src="{{ img }}" alt="Analysis Image">
            </div>
        </div>

    </div>

    <div class="col">
        {% if result.prob == 0 %}
        <div class="card border-2 shadow mb-4" style="background-color: rgba(102, 255, 14, 0.116);">
        {% else %}
        <div class="card border-2 shadow mb-4" style="background-color: rgba(255, 14, 14, 0.116);">
        {% endif %}
            <div class="card-body text-center">
                <h3><span class="text-muted">Disease:</span>      {{ result.label }}</h3><br>
                <h3><span class="text-muted">Likelihood:</span>   {{ result.prob }}<span>&#37;</span></h3>
            </div>
        </div>
    </div>
    <div class="col-1"></div>

</div>
{% endif %}




{% endblock content %}




<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

templates/doctor/confirm_appointment.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}

{% if appoint.status == 'pending' %}
     Confirm Appointment 
{% else %}
    Update Appointment 
{% endif %}

{% endblock %} 



<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}




{% block content %}

<div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item">
                <a href="{% url 'doctor:dashboard' %}">
                    <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </a>
            </li>

            <li class="breadcrumb-item"><a href="{% url 'doctor:appointment' %}">Appointments</a></li>
            {% if appoint.status == 'pending' %}
            <li class="breadcrumb-item active" aria-current="page">Confirm</li>
            {% else %}
            <li class="breadcrumb-item active" aria-current="page">Update</li>
            {% endif %}
            
        </ol>
    </nav>
    <div class="d-flex justify-content-between w-100 flex-wrap">
        <div class="mb-3 mb-lg-0">

            {% if appoint.status == 'pending' %}
            <h1 class="h4">Confirm Appointment</h1>
            {% else %}
            <h1 class="h4">Update Appointment</h1>
            {% endif %}
        </div>
    </div>
</div>

<div class="row">

    <div class="col-1"></div>
    <div class="col">
        <div class="card border-0 shadow mb-4">

            <!-- <div class="card-header">Description</div> -->
            <div class="card-body">


                <form action="" method="post">
                    <div class="accordion" id="accordionPanelsStayOpenExample">

                        <!-- PATIENT INFO -->
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                                PATIENT INFO
                              </button>
                            </h2>
                            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                              <div class="accordion-body">
                                <ul style="color: black;">
                                      <li><strong>Patient's Name:&emsp;&emsp;</strong>{{ appoint.patient.get_full_name }}</li><br>
                                      <li><strong>Patient's Age:&emsp;&emsp;</strong>{{ appoint.patient.dob }}</li><br>       <!-- MUST ADD AGE ATTRIBUTE TO MODEL AND CHANGE HERE -->
                                      <li><strong>Patient's Gender:&emsp;&emsp;</strong>{{ appoint.patient.get_gender_display }}</li><br>
                                </ul>
                              </div>
                            </div>
                        </div>


                        <!-- DETAILS -->
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="true" aria-controls="panelsStayOpen-collapseTwo">
                                    DETAILS
                                </button>
                              </h2>
                              <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingTwo">
                                <div class="accordion-body">
                                  <ul style="color: black;">
                                    <li><strong>Appointment Type:&emsp;&emsp;</strong>{{ appoint.get_types_display }}</li><br>
                                    <li><strong>Appointment Status:&emsp;&emsp;</strong>{{ appoint.get_status_display }}</li><br>
                                  </ul>
                                </div>
                              </div>
                        </div>


                        <!-- DATE AND TIME -->
                          <div class="accordion-item">
                              <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="true" aria-controls="panelsStayOpen-collapseThree">
                                      DATE AND TIME
                                  </button>
                                </h2>
                                <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingThree">
                                  <div class="accordion-body">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                  </div>
                                </div>
                          </div>


                            <!-- DESCRIPTION -->
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="panelsStayOpen-headingFour">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="true" aria-controls="panelsStayOpen-collapseFour">
                                        DESCRIPTION
                                    </button>
                                </h2>
                            <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingFour">
                                <div class="accordion-body">
                                    <ul style="color: black;">
                                        <li>{{ appoint.description }}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        
                    </div><br>

                    <div class="container-fluid">
                        {% if appoint.status == 'pending' %}
                        <button type="submit" class="btn btn-warning">Confirm Appointment</button>
                        <a href="{% url 'doctor:cancel' appoint.id %}"><button class="btn btn-danger">Cancel Appointment</button></a>
                        {% elif appoint.status == 'confirmed' %}
                        <button type="submit" class="btn btn-info">Update Appointment</button>
                        <a href="{% url 'doctor:cancel' appoint.id %}"><button class="btn btn-danger">Cancel Appointment</button></a>
                        {% endif %}
                    </div>
                </form>


            </div>


        </div>
    </div>
    <div class="col-1"></div>

</div>


{% endblock content %}




<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/doctor/patient_detail.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %} Tables {% endblock %} 



<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}




{% block content %}

<div class="py-4">
    <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
        <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
            <li class="breadcrumb-item">
                <a href="{% url 'doctor:dashboard' %}">
                    <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                </a>
            </li>

            <li class="breadcrumb-item"><a href="{% url 'doctor:appointment' %}">Appointments</a></li>
            <li class="breadcrumb-item active" aria-current="page">Patient Detail</li>
        </ol>
    </nav>
    <div class="d-flex justify-content-between w-100 flex-wrap">
        <div class="mb-3 mb-lg-0">

            
            <h1 class="h4">Patient Details </h1>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-1"></div>
    <div class="col">
        <div class="card border-0 shadow mb-4">

            <!-- <div class="card-header">Description</div> -->
            <div class="card-body">





            </div>
        
        
        </div>
    </div>
    <div class="col-1"></div>

</div>


{% endblock content %}




<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}