Patient/urls.py
from django.urls import path, include

from . import views

app_name = "Patient"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('appointment', views.Appointment.as_view(), name='appointment'),
    path('appointment/past', views.PastAppointment.as_view(), name='past_appointments'),
    path('appointment/add', views.AddAppointment.as_view(), name='add_appointment'),
    path('appointment/<int:pk>/cancel', views.CancelAppointment.as_view(), name='cancel'),
    path('reports', views.Reports.as_view(), name='reports'),
]

administrator/urls.py
from django.urls import path, include

from . import views

app_name = "administrator"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('users', views.User.as_view(), name='users'),
    path('appointments', views.Appointment.as_view(), name='appointments'),
    path('reports', views.Report.as_view(), name='reports'),
    path('referals', views.Referal.as_view(), name='referals'),
    path('users/<int:id>/details', views.Account_detail.as_view(), name='account_detail'),
    path('users/<int:id>/delete', views.DeleteUser.as_view(), name='delete_user'),
    path('appointments/<int:id>/details', views.Appointment_detail.as_view(), name='appointment_detail'),
    path('appointments/<int:id>/delete', views.DeleteAppointment.as_view(), name='delete_appointment'),
    path('appointment/add', views.AddAppointment.as_view(), name='appointment_add'),
    path('reports/<int:id>/details', views.Report_detail.as_view(), name='reports_detail'),
    path('reports/<int:id>/delete', views.DeleteReport.as_view(), name='delete_reports'),
    path('reports/rad/add', views.AddRadReport.as_view(), name='radreport_add'),
    path('reports/med/add', views.AddMedReport.as_view(), name='medreport_add'),
    path('referals/<int:id>/detail', views.Referal_detail.as_view(), name='referal_detail'),
    path('referals/<int:id>.delete', views.DeleteReferal.as_view(), name='delete_referal'),
    path('referals/add', views.AddReferal.as_view(), name='referal_add'),
    
]

core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "core"

urlpatterns = [
    path('', views.landing_page, name='landing'),
]

if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path, include

from . import views

app_name = "doctor"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('appointment', views.Appointment.as_view(), name='appointment'),
    path('appointment/past', views.PastAppointment.as_view(), name='past_appointments'),
    path('appointment/<int:pk>/update', views.UpdateAppointment.as_view(), name='update'),
    path('appointment/<int:pk>/cancel', views.CancelAppointment.as_view(), name='cancel'),
    path('appointment/<int:pk>/complete', views.CompleteAppointment.as_view(), name='complete'),
    path('appointment/<int:pk>/start', views.StartAppointment.as_view(), name='start'),
    path('patient/<int:id>', views.Patient_detail.as_view(), name='patient_detail'),
    path('chest-analysis', views.Analysis.as_view(), name='analysis')
    
]

fypDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import landing_page



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('doctor/', include('doctor.urls') ),
    path('administrator/', include('administrator.urls') ),
    path('radiologist/', include('radiologist.urls') ),
    path('patient/', include('Patient.urls') ),
    path('', include('core.urls') ),
    path('register/', include('register.urls')),
    path('', include("django.contrib.auth.urls")),
]

radiologist/urls.py
from django.urls import path, include

from . import views

app_name = "radiologist"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('chest-analysis', views.Analysis.as_view(), name='analysis'),
    path('referal', views.Referal.as_view(), name='referal'),
    path('referal/past', views.PastReferal.as_view(), name='past'),
    path('referal/<int:pk>/start', views.ReferalStart.as_view(), name='start'),
    path('referal/<int:pk>/cancel', views.ReferalCancel.as_view(), name='cancel'),
]

templates/includes/sidebars/administrator_sidebar.html
{% load static %}  



        
        <nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
          <div class="sidebar-inner px-4 pt-3">


            <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
              <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                  <img src="/static/assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white"
                    alt="Bonnie Green">
                </div>
                <div class="d-block">
                  <h2 class="h5 mb-3">Hi, Jane</h2>
                  <a href="/page-sign-in.html" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                    <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>            
                    Sign Out
                  </a>
                </div>
              </div> 
              <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                  </a>
              </div>
            </div>


            <ul class="nav flex-column pt-3 pt-md-0">


              <li class="nav-item">
                <a href="/" class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <img src="{% static 'myassets/image/logo.png' %}" alt="Medical AI Logo">
                  </span>

                </a>
              </li>

              <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>

              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'administrator:dashboard' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
                  </span> 
                  <span class="sidebar-text">Dashboard</span>
                </a>
              </li>


              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'administrator:users' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-users"></i>
                  </span> 
                  <span class="sidebar-text">Users</span>
                </a>
              </li>



              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'administrator:appointments' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-calendar-check"></i>
                  </span> 
                  <span class="sidebar-text">Appointments</span>
                </a>
              </li>



              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'administrator:reports' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-id-badge"></i>
                  </span> 
                  <span class="sidebar-text">Reports</span>
                </a>
              </li>



              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'administrator:referals' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-file-alt"></i>
                  </span> 
                  <span class="sidebar-text">Referals</span>
                </a>
              </li>

              
            </ul>


          </div>
        </nav>

templates/includes/sidebars/doctor_sidebar.html
{% load static %}  



        
        <nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
          <div class="sidebar-inner px-4 pt-3">


            <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
              <div class="d-flex align-items-center">
                <div class="avatar-lg me-4">
                  <img src="/static/assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white"
                    alt="Bonnie Green">
                </div>
                <div class="d-block">
                  <h2 class="h5 mb-3">Hi, Jane</h2>
                  <a href="/page-sign-in.html" class="btn btn-secondary btn-sm d-inline-flex align-items-center">
                    <svg class="icon icon-xxs me-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>            
                    Sign Out
                  </a>
                </div>
              </div> 
              <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" data-bs-toggle="collapse"
                    data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation">
                    <svg class="icon icon-xs" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                  </a>
              </div>
            </div>


            <ul class="nav flex-column pt-3 pt-md-0">


              <li class="nav-item">
                <a href="/" class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <img src="{% static 'myassets/image/logo.png' %}" alt="Medical AI Logo">
                  </span>

                </a>
              </li>

              <li role="separator" class="dropdown-divider mt-4 mb-3 border-gray-700"></li>

              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'doctor:dashboard' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
                  </span> 
                  <span class="sidebar-text">Dashboard</span>
                </a>
              </li>

              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'doctor:appointment' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-calendar-alt"></i>
                  </span>
                  <span class="sidebar-text">Current Appointments</span>
                </a>
              </li>

              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'doctor:past_appointments' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-calendar-check"></i>
                  </span>
                  <span class="sidebar-text">Past Appointments</span>
                </a>
              </li>


              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'doctor:analysis' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-project-diagram"></i>
                  </span>
                  <span class="sidebar-text">Chest Analysis</span>
                </a>
              </li>

              
            </ul>


          </div>
        </nav>

templates/includes/sidebars/patient_sidebar.html
{% load static %}  



        
        <nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
          <div class="sidebar-inner px-4 pt-3">


            <ul class="nav flex-column pt-3 pt-md-0">


            
              <li class="nav-item">
                <a href="/" class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <img src="{% static 'myassets/image/logo.png' %}" alt="Medical AI Logo">
                  </span>

                </a>
              </li>


              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'Patient:dashboard' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
                  </span> 
                  <span class="sidebar-text">Dashboard</span>
                </a>
              </li>


              <li class="nav-item {% if 'page-' in segment %} active {% endif %}">
                <span
                  class="nav-link  collapsed  d-flex justify-content-between align-items-center"
                  data-bs-toggle="collapse" data-bs-target="#submenu-pages">
                  <span>
                    <span class="sidebar-icon">
                      <i class="fas fa-calendar-check"></i>
                    </span> 
                    <span class="sidebar-text"> Appointments </span>
                  </span>
                  <span class="link-arrow">
                    <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                  </span>
                </span>
                <div class="multi-level collapse {% if 'page-' in segment %} show {% endif %} " role="list"
                  id="submenu-pages" aria-expanded="false">
                  <ul class="flex-column nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'Patient:appointment' %}">
                        <span class="sidebar-text">Current Appointments</span>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'Patient:past_appointments' %}">
                        <span class="sidebar-text">Past Appointments</span>
                      </a>
                    </li>
                  </ul>
                </div>
              </li>


              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'Patient:add_appointment' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-calendar-plus"></i>
                  </span>
                  <span class="sidebar-text">Reserve Appointment</span>
                </a>
              </li>


              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'Patient:reports' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-file-alt"></i>
                  </span>
                  <span class="sidebar-text">Reports</span>
                </a>
              </li>

              
            </ul>


          </div>
        </nav>

templates/includes/sidebars/radiologist_sidebar.html
{% load static %}  



        
        <nav id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
          <div class="sidebar-inner px-4 pt-3">



            <ul class="nav flex-column pt-3 pt-md-0">


            
              <li class="nav-item">
                <a href="/" class="nav-link d-flex align-items-center">
                  <span class="sidebar-icon">
                    <img src="{% static 'myassets/image/logo.png' %}" alt="Medical AI Logo">
                  </span>

                </a>
              </li>


              <li class="nav-item {% if 'dashboard' in segment %} active {% endif %}">
                <a href="{% url 'radiologist:dashboard' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
                  </span> 
                  <span class="sidebar-text">Dashboard</span>
                </a>
              </li>


              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'radiologist:referal' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-file-alt"></i>
                  </span>
                  <span class="sidebar-text">Current Referals</span>
                </a>
              </li>


              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'radiologist:past' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-check"></i>
                  </span>
                  <span class="sidebar-text">Past Referals</span>
                </a>
              </li>

              <li class="nav-item {% if 'settings' in segment %} active {% endif %}">
                <a href="{% url 'radiologist:analysis' %}" class="nav-link">
                  <span class="sidebar-icon">
                    <i class="fas fa-project-diagram"></i>
                  </span>
                  <span class="sidebar-text">Chest Analysis</span>
                </a>
              </li>

              
            </ul>


          </div>
        </nav>