administrator/urls.py
from django.urls import path, include

from . import views

app_name = "administrator"
urlpatterns = [
    path('dashboard', views.Dash.as_view(), name='dashboard'),
    path('users', views.User.as_view(), name='users'),
    path('appointments', views.Appointment.as_view(), name='appointments'),
    path('reports', views.Report.as_view(), name='reports'),
    path('referals', views.Referal.as_view(), name='referals'),
    path('users/<int:id>/details', views.Account_detail.as_view(), name='account_detail'),
    path('users/<int:id>/delete', views.DeleteUser.as_view(), name='delete_user'),
    path('appointments/<int:id>/details', views.Appointment_detail.as_view(), name='appointment_detail'),
    path('appointments/<int:id>/delete', views.DeleteAppointment.as_view(), name='delete_appointment'),
    path('appointment/add', views.AddAppointment.as_view(), name='appointment_add'),
    path('reports/<int:id>/details', views.Report_detail.as_view(), name='reports_detail'),
    path('reports/<int:id>/delete', views.DeleteReport.as_view(), name='delete_reports'),
    path('reports/rad/add', views.AddRadReport.as_view(), name='radreport_add'),
    path('reports/med/add', views.AddMedReport.as_view(), name='medreport_add'),
    path('referals/<int:id>/detail', views.Referal_detail.as_view(), name='referal_detail'),
    path('referals/<int:id>.delete', views.DeleteReferal.as_view(), name='delete_referal'),
    path('referals/add', views.AddReferal.as_view(), name='referal_add'),
    
]

core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "core"

urlpatterns = [
    path('', views.landing_page, name='landing'),
]

if settings.DEBUG:urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

fypDjango/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import landing_page



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('doctor/', include('doctor.urls') ),
    path('administrator/', include('administrator.urls') ),
    path('radiologist/', include('radiologist.urls') ),
    path('patient/', include('Patient.urls') ),
    path('', include('core.urls') ),
    path('register/', include('register.urls')),
    path('', include("django.contrib.auth.urls")),
]

administrator/models.py
from django.db import models

# Create your models here.

core/models.py
from datetime import date
from django.db import models
from register.models import Patient, Radiologist, Doctor



# APPOINTMENT MODEL
TYPES = (('consult', 'Consultation'), ('follow', 'Follow-up'),)
STATUS = (('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'),)

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, related_name='appoint_patient')
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, related_name='appoint_doctor')
    description = models.TextField()
    date = models.DateField('Date')
    start_time = models.TimeField('Start Time', null=True)
    types = models.CharField(max_length=100, choices=TYPES)
    status = models.CharField(max_length=100, choices=STATUS)
    mcheck = models.BooleanField(default=False)
    rcheck = models.BooleanField(default=False)

    def __str__(self):
        return str(self.date)




# GLOBAL VARIABLES
Rad_types = (
    ('x', 'X-Ray'),
    ('ct', 'CT-Scan'),
    ('mri', 'MRI'),
    ('ot', 'Others'),
)

Body_location = (
    ('ab', 'Abdomen'),
    ('ch', 'Chest'),
    ('pl', 'Pelvis'),
    ('ue', 'Upper Extremities'),
    ('le', 'Lower Extremities'),
    ('sp', 'Spine'),
    ('hnf', 'Head, Neck and Face'),
    ('ot', 'Others'),
)




# REPORTS MODEL
Rep_type = (
    ('rad', 'Radiology'),
    ('med', 'Medical'),
)

class Report(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, related_name='report_patient')
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True, related_name='report_doctor')
    radiologist = models.ForeignKey(Radiologist, on_delete=models.SET_NULL, null=True, blank=True, related_name='report_radiologist')
    report_type = models.CharField('Report Type', max_length=100, choices=Rep_type)
    date = models.DateField('Date', default=date.today)
    analysis = models.TextField('Analysis', null=True, blank=True)
    comments = models.TextField('Comments', null=True, blank=True)
    
    def __str__(self):
        return str(self.report_type)



class RadManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(report_type='rad')

class MedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(report_type='med')



class Radreport(Report):
    objects = RadManager()
    rad_types = models.CharField('Test Type', max_length=100, choices=Rad_types, default='ot')
    body = models.CharField('Body Location', max_length=100, choices=Body_location, default='ot')
    rad_image = models.ImageField(upload_to='rad_reports/', null = True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.report_type = 'rad'
        return super().save(*args, **kwargs)


class Medreport(Report):
    objects = MedManager()
    visit_reason = models.TextField('Visit Reason', null = True, blank=True)
    Prescription = models.TextField('Prescription', null = True, blank=True)
    med_image = models.ImageField(upload_to='med_reports/', null = True, blank=True)
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.report_type = 'med'
        return super().save(*args, **kwargs)






# REFERAL MODAL
ref_status = (
    ('pending', 'Pending'),
    ('completed', 'Completed'),
    ('cancelled', 'Cancelled')
)

class Referal(models.Model):
        patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True, related_name='referal_patient')
        rad_report = models.ForeignKey(Radreport, on_delete=models.SET_NULL, null=True, blank=True, related_name='rad_report')    #similar as radrep. Reso;ve this issue
        doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True, blank=True, related_name='referal_doctor')
        radiologist = models.ForeignKey(Radiologist, on_delete=models.SET_NULL, null=True, blank=True, related_name='referal_radiologist')  #Radiologist is mandotory
        rad_types = models.CharField('Test Type', max_length=100, choices=Rad_types, default='ot', blank=True)
        body = models.CharField('Body Location', max_length=100, choices=Body_location, default='ot', blank=True)
        description = models.TextField('Description', null=True, blank=True)    #Description is Mandatory
        status = models.CharField('Status', max_length=100, choices=ref_status, default='pending')
        date = models.DateField('Date', default=date.today)
        radrep = models.ForeignKey(Radreport, on_delete=models.DO_NOTHING, null=True, blank=True)
        
        def __str__(self):
            return str(self.rad_types)

administrator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
import os
from pathlib import Path


from django.contrib import messages
from .forms import PatientForm, DoctorForm, RadiologistForm, AppointmentForm, MedReportForm, RadReportForm, ReferalForm
from register.models import Patient, Doctor, Radiologist, CustomUser
from core.models import Appointment as apt
from core.models import Radreport as rrep
from core.models import Medreport as mrep
from core.models import Report as trep
from core.models import Referal as refer


#  GLOBAL VARIABLE
baseDr = Path(__file__).resolve().parent.parent



# DASHBOARD INDEX VIEW
class Dash(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'a':
            return render(request, 'administrator/dashboard.html', {'type':request.user.account_type})
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')










# USERS LIST VIEW
class User(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'a':
            
            usr = CustomUser.objects.all().exclude(account_type='a')
            return render(request, 'administrator/users.html', {'list':usr, 'type':request.user.account_type}) 
            
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# USER ACCOUNT DETAIL
class Account_detail(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    
    def get(self, request, id):
        
        if request.user.account_type == 'a':
        
            cuser = CustomUser.objects.get(pk=id)
            if cuser.account_type == 'p':
                
                pat = Patient.objects.get(pk=id)
                pform = PatientForm(instance = pat)
                
                return render(request, "administrator/user_detail.html", {'form':pform, 'type':request.user.account_type, 'user_type':cuser.account_type, 'user_id':cuser.id})
                
            elif cuser.account_type == 'd':
                
                doc = Doctor.objects.get(pk=id)
                dform = DoctorForm(instance = doc)
                
                return render(request, "administrator/user_detail.html", {'form':dform, 'type':request.user.account_type, 'user_type':cuser.account_type, 'user_id':cuser.id})
                
            elif cuser.account_type == 'r':
                
                rad = Radiologist.objects.get(pk=id)
                rform = RadiologistForm(instance = rad)
                
                return render(request, "administrator/user_detail.html", {'form':rform, 'type':request.user.account_type, 'user_type':cuser.account_type, 'user_id':cuser.id})
        
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')
    
    
    def post(self, request, id):
        
        if request.user.account_type == 'a':
        
            cuser = CustomUser.objects.get(pk=id)
            if cuser.account_type == 'p':
                
                pat = Patient.objects.get(pk=id)
                form = PatientForm(request.POST, instance=pat)
                
                if not form.is_valid():
                    return render(request, "administrator/user_detail.html", {'form':form, 'type':request.user.account_type, 'user_type':cuser.account_type, 'user_id':cuser.id})
                else:
                    form.save()
                    return redirect("administrator:users")
                
            elif cuser.account_type == 'd':
                
                doc = Doctor.objects.get(pk=id)
                dform = DoctorForm(request.POST, instance=doc)
                if not dform.is_valid():
                    return render(request, "administrator/user_detail.html", {'form':dform, 'type':request.user.account_type, 'user_type':cuser.account_type, 'user_id':cuser.id})
                
                dform.save()
                return redirect("administrator:users")
                
            elif cuser.account_type == 'r':
                
                rad = Radiologist.objects.get(pk=id)
                rform = RadiologistForm(request.POST, instance=rad)
                if not rform.is_valid():
                    return render(request, "administrator/user_detail.html", {'form':rform, 'type':request.user.account_type, 'user_type':cuser.account_type, 'user_id':cuser.id})
                
                rform.save()
                return redirect("administrator:users")
        
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# DELETE USER ACCOUNT
class DeleteUser(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request, id):
        
        if request.user.account_type == 'a':
            cuser = CustomUser.objects.get(pk=id)
            cuser.delete()
            return redirect("administrator:users")
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')











# APPOINTMENTS LIST VIEW
class Appointment(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'a':
            
            appoint = apt.objects.all().order_by('-date', '-start_time')
            return render(request, 'administrator/appointments.html', {'list':appoint, 'type':request.user.account_type}) 
            
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')
        




# APPOINTMENT DETAIL
class Appointment_detail(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request, id):
        
        if request.user.account_type == 'a':
            
            appoint = apt.objects.get(pk=id)
            form = AppointmentForm(instance=appoint)
            return render(request, 'administrator/appointments_detail.html', {'form':form, 'type':request.user.account_type, 'appoint_id':appoint.id}) 
            
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')
        
        
    def post(self, request, id):
        
        if request.user.account_type == 'a':
            
            appoint = apt.objects.get(pk=id)
            form = AppointmentForm(request.POST, instance=appoint)
            
            if not form.is_valid():
                return render(request, 'administrator/appointments_detail.html', {'form':form, 'type':request.user.account_type, 'appoint_id':appoint.id})  
            
            form.save()
            return redirect("administrator:appointments")
        
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# DELETE APPOINTMENT
class DeleteAppointment(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request, id):
        
        if request.user.account_type == 'a':
                appoint = apt.objects.get(pk=id)
                appoint.delete()
                return redirect("administrator:appointments")
        
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')




# ADD APPOINTMENT
class AddAppointment(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    def get(self, request):
        
        if request.user.account_type == 'a':
            form = AppointmentForm()
            return render(request, "administrator/Add_appointment.html", {'form':form, 'type':request.user.account_type})
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')

    def post(self, request):
        
        form = AppointmentForm(request.POST)
        
        if not form.is_valid():
            return render(request, "administrator/Add_appointment.html", {'form':form, 'type':request.user.account_type})
        
        form.save()
        messages.success(request, 'Appointment has been successfully created')
        return redirect("administrator:appointments")









# REPORTS LIST VIEW
class Report(LoginRequiredMixin, View):
    
    def get(self, request):
        
        if request.user.account_type == 'a':
            
            rep = trep.objects.all().order_by('-date')
            return render(request, 'administrator/reports.html', {'list':rep, 'type':request.user.account_type}) 
            
        else:
            messages.success(request, 'Yikes! Seems like you were accessing something you shouldn\'t have ')
            return redirect('core:landing')



# REPORT DETAIL
class Report_detail(LoginRequiredMixin, View):
    
    login_url = '/login/'
    
    
    def get(self, request, id):
        
        if request.user.account_type == 'a':
        
            rep = trep.objects.get(pk=id)
            if rep.report_type == 'rad':
                
                radrep = rrep.objects.get(pk=id)
                rform = RadReportForm(instance = radrep)
                

templates/administrator/reports.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_tags %}



{% block title %} Reports {% endblock %} 



<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}




{% block content %}

  <div class="py-4">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
          <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
              <li class="breadcrumb-item">
                  <a href="{% url 'administrator:dashboard' %}">
                      <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                  </a>
              </li>

              <li class="breadcrumb-item active" aria-current="page">Reports</li>
          </ol>
      </nav>
      <div class="d-flex justify-content-between w-100 flex-wrap">
          <div class="mb-3 mb-lg-0">

            
            <div class="dropdown">
                <button class="btn btn-secondary d-inline-flex align-items-center me-2 dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg class="icon icon-xs me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
                    Add Report
                </button>
                <div class="dropdown-menu dashboard-dropdown dropdown-menu-start mt-2 py-1">
                    <a class="dropdown-item d-flex align-items-center" href="{% url 'administrator:radreport_add' %}">
                        Add Radiology Report
                    </a>
                    <a class="dropdown-item d-flex align-items-center" href="{% url 'administrator:medreport_add' %}">
                        Add Medical Report
                    </a>
                </div>
            </div>
          </div>
      </div>
  </div>


  {% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}


  <div class="card border-0 shadow mb-4">

    <div class="card-body">

        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab" aria-controls="nav-home" aria-selected="true">All</button>
                <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#medical" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Medical</button>
                <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#radiology" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Radiology</button>
            </div>
          </nav>
          <div class="tab-content" id="nav-tabContent">



            <!-- MEDICAL STARTS HERE -->
            <div class="tab-pane fade" id="medical" role="tabpanel" aria-labelledby="nav-profile-tab">

                <br>
                <div class="table-responsive">
                    <table class="table table-centered table-nowrap mb-0 rounded">
                        <thead class="thead-light text-center">
                            <tr>
                                <th class="border-0 rounded-start">Patient's Name</th>
                                <th class="border-0">Doctor's Name</th>
                                <th class="border-0">Radiologist's Name</th>
                                <th class="border-0">Date</th>
                                <th class="border-0">Type</th>
                                <th class="border-0">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
        
                            {% if list %}
        
                                {% for rep in list %}
                                {% if rep.report_type == 'med' %}

                                        <!-- Item -->
                                        <tr class="text-center">
                                            <td class="fw-bold"> {{ rep.patient.get_full_name }} </td>

                                            <td class="fw-bold">
                                                {{rep.doctor.get_full_name}}
                                            </td>

                                            <td class="fw-bold">
                                                <strong style="color: red;">N/A</strong>
                                            </td>

                                            <td>
                                                {{ rep.date }}
                                            </td>

                                            <td>
                                                {{rep.get_report_type_display}}
                                            </td>

                                            <td>
                                                <a href="{% url 'administrator:reports_detail' rep.id %}"><button class="btn btn-outline-primary">View Details</button></a>
                                                <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delconfirm{{rep.id}}">Delete</button>
                                            </td>
                                        </tr>
                                        <!-- End of Item -->

                                {% endif %}
                                {% endfor %}
        
                            {% endif %}
        
        
        
                        </tbody>
                    </table>
                </div>


            </div>
            <!-- ENDS HERE -->



            <!-- RADIOLOGY STARTS HERE -->
            <div class="tab-pane fade" id="radiology" role="tabpanel" aria-labelledby="nav-home-tab">


                <br>
                <div class="table-responsive">
                    <table class="table table-centered table-nowrap mb-0 rounded">
                        <thead class="thead-light text-center">
                            <tr>
                                <th class="border-0 rounded-start">Patient's Name</th>
                                <th class="border-0">Doctor's Name</th>
                                <th class="border-0">Radiologist's Name</th>
                                <th class="border-0">Date</th>
                                <th class="border-0">Type</th>
                                <th class="border-0">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
        
                            {% if list %}
        
                                {% for rep in list %}
                                {% if rep.report_type == 'rad' %}

                                        <!-- Item -->
                                        <tr class="text-center">
                                            <td class="fw-bold"> {{ rep.patient.get_full_name }} </td>

                                            <td class="fw-bold">
                                                {{rep.doctor.get_full_name}}
                                            </td>

                                            <td class="fw-bold">
                                                {{rep.radiologist.get_full_name}}
                                            </td>

                                            <td>
                                                {{ rep.date }}
                                            </td>

                                            <td>
                                                {{rep.get_report_type_display}}
                                            </td>

                                            <td>
                                                <a href="{% url 'administrator:reports_detail' rep.id %}"><button class="btn btn-outline-primary">View Details</button></a>
                                                <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delconfirm{{rep.id}}">Delete</button>
                                            </td>
                                        </tr>
                                        <!-- End of Item -->

                                {% endif %}
                                {% endfor %}
        
                            {% endif %}
        
        
        
                        </tbody>
                    </table>
                </div>


            </div>
            <!-- ENDS HERE -->



            <!-- ALL STARTS HERE -->
            <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="nav-contact-tab">


                <br>
                <div class="table-responsive">
                    <table class="table table-centered table-nowrap mb-0 rounded">
                        <thead class="thead-light text-center">
                            <tr>
                                <th class="border-0 rounded-start">Patient's Name</th>
                                <th class="border-0">Doctor's Name</th>
                                <th class="border-0">Radiologist's Name</th>
                                <th class="border-0">Date</th>
                                <th class="border-0">Type</th>
                                <th class="border-0">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
        
                            {% if list %}
        
                                {% for rep in list %}

                                        <!-- Item -->
                                        <tr class="text-center">
                                            <td class="fw-bold"> {{ rep.patient.get_full_name }} </td>

                                            <td class="fw-bold">
                                                {{rep.doctor.get_full_name}}
                                            </td>

                                            <td class="fw-bold">
                                                {% if rep.report_type == 'med' %}
                                                <strong style="color: red;">N/A</strong>
                                                {% else %}
                                                {{rep.radiologist.get_full_name}}
                                                {% endif %}
                                            </td>

                                            <td>
                                                {{ rep.date }}
                                            </td>

                                            <td>
                                                {{rep.get_report_type_display}}
                                            </td>

                                            <td>
                                                <a href="{% url 'administrator:reports_detail' rep.id %}"><button class="btn btn-outline-primary">View Details</button></a>
                                                <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delconfirm{{rep.id}}">Delete</button>
                                            </td>
                                        </tr>
                                        <!-- End of Item -->

                                {% endfor %}
        
                            {% endif %}
        
        
        
                        </tbody>
                    </table>
                </div>


            </div>
            <!-- ENDS HERE -->

        </div>
    </div>




    <!-- DELETION CONFIRMATION -->
    {% for rep in list %}
    <div class="modal fade" id="delconfirm{{rep.id}}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title">Confirm Deletion</h5>
            </div>
            <div class="modal-body text-center">
                
                <h2 style="color: red;"> ARE YOU SURE ? </h2><br>
                <p class="text-muted">If Deleted this record can't be recovered</p>

            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel</button>
            <a href="{% url 'administrator:delete_reports' rep.id %}"><button type="button" class="btn btn-outline-danger">Delete</button></a>
            </div>
        </div>
        </div>
    </div>
    {% endfor %}

  
  </div>


{% endblock content %}




<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}